- name: Deploy App
  hosts: localhost

  vars:
    image_name: "{{ lookup('env', 'DOCKER_USERNAME') }}/devops-demo-app:latest"

  tasks:

    - name: Pull latest Docker image
      docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: Run container
      docker_container:
        name: devops-app
        image: "{{ image_name }}"
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
