- name: Deploy App
  hosts: localhost
  

  vars:
    image_name: "yourdockerhub/devops-demo:1.0"

  tasks:
    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Run container from local image
      docker_container:
        name: devops-app
        image: "devops-demo-app"
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
